spring.application.name=springboot-app
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:h2:file:./springboot_appdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
# Use physical naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

#turn off stack trace on an exception
server.error.include-stacktrace=never

#comment/uncomment if you want DatabaseInit.java to iniatialise the database
spring.profiles.active=databaseinit
spring.jpa.hibernate.ddl-auto = update

# JWT Configuration
jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
jwt.expiration=86400000
